FROM python:3.6
MAINTAINER ajgil <antonoiojesusgil@gmail.com>

/app
pip3 install beautifulsoup4 \ &&
flask \ &&
requests /app/

main.py /app/
linkextractor.py /app/
chmod a+x *.py

python3 /app/main.py
