FROM python:3.6
MAINTAINER ajgil <antonoiojesusgil@gmail.com>

pip3 install beautifulsoup4
pip3 install flask
pip3 install requests

/app

main.py /app/
linkextractor.py /app/
chmod a+x *.py

python3 /app/main.py
